require('dotenv').config();

const PORT = process.env.PORT || 4000;
const BASE_URL = process.env.BASE_URL || `http://localhost:${PORT}`;
const FRONTEND_URL = process.env.FRONTEND_URL || 'http://localhost:3000';
const PASS_URL = process.env.PASS_URL;
const QUIZ_PASS_PERCENT = Number(process.env.QUIZ_PASS_PERCENT || 60);

const MONGO_URI = process.env.MONGO_URI;

const HUBSPOT_CLIENT_ID = process.env.HUBSPOT_CLIENT_ID;
const HUBSPOT_CLIENT_SECRET =
  process.env.HUBSPOT_CLIENT_SECRET || process.env.HUBSPOT_CLIENT_SERCRET;

const HUBSPOT_REDIRECT_URI = (process.env.HUBSPOT_REDIRECT_URI || `${BASE_URL}/api/auth/callback`).trim();

const HUBSPOT_ACCEPTANCE_STAGE_ID = process.env.HUBSPOT_ACCEPTANCE_STAGE_ID;
const HUBSPOT_ASSESSMENTS_STAGE_ID = process.env.HUBSPOT_ASSESSMENTS_STAGE_ID;

// Alias so your services stay readable
const HUBSPOT_STAGE_ACCEPTANCE_LETTER =
  process.env.HUBSPOT_STAGE_ACCEPTANCE_LETTER || HUBSPOT_ACCEPTANCE_STAGE_ID;

const HUBSPOT_STAGE_ASSESSMENTS =
  process.env.HUBSPOT_STAGE_ASSESSMENTS || HUBSPOT_ASSESSMENTS_STAGE_ID;

const GRAPH_CLIENT_ID = process.env.GRAPH_CLIENT_ID;
const GRAPH_CLIENT_SECRET = process.env.GRAPH_CLIENT_SECRET;
const GRAPH_TENANT_ID = process.env.GRAPH_TENANT_ID;
const GRAPH_SENDER_EMAIL = process.env.GRAPH_SENDER_EMAIL;

module.exports = {
  PORT,
  BASE_URL,
  FRONTEND_URL,
  MONGO_URI,
  PASS_URL,
  QUIZ_PASS_PERCENT,

  HUBSPOT_CLIENT_ID,
  HUBSPOT_CLIENT_SECRET,
  HUBSPOT_REDIRECT_URI,

  HUBSPOT_ACCEPTANCE_STAGE_ID,
  HUBSPOT_ASSESSMENTS_STAGE_ID,
  HUBSPOT_STAGE_ACCEPTANCE_LETTER,
  HUBSPOT_STAGE_ASSESSMENTS,

  GRAPH_CLIENT_ID,
  GRAPH_CLIENT_SECRET,
  GRAPH_TENANT_ID,
  GRAPH_SENDER_EMAIL,

  isGraphEmailConfigured: () =>
    !!(GRAPH_CLIENT_ID && GRAPH_CLIENT_SECRET && GRAPH_TENANT_ID && GRAPH_SENDER_EMAIL),
};
