require('dotenv').config();

const PORT = process.env.PORT || 4000;
const BASE_URL = process.env.BASE_URL || `http://localhost:${PORT}`;
const FRONTEND_URL = process.env.FRONTEND_URL || 'http://localhost:3000';
const PASS_URL = process.env.PASS_URL;
const QUIZ_PASS_PERCENT = Number(process.env.QUIZ_PASS_PERCENT || 60);

const MONGO_URI = process.env.MONGO_URI;

const HUBSPOT_CLIENT_ID = process.env.HUBSPOT_CLIENT_ID;
const HUBSPOT_CLIENT_SECRET =
  process.env.HUBSPOT_CLIENT_SECRET || process.env.HUBSPOT_CLIENT_SERCRET;

const HUBSPOT_REDIRECT_URI = (process.env.HUBSPOT_REDIRECT_URI || `${BASE_URL}/api/auth/callback`).trim();

const HUBSPOT_ACCEPTANCE_STAGE_ID = process.env.HUBSPOT_ACCEPTANCE_STAGE_ID;
const HUBSPOT_ASSESSMENTS_STAGE_ID = process.env.HUBSPOT_ASSESSMENTS_STAGE_ID;
const HUBSPOT_PIPELINE_ID = process.env.HUBSPOT_PIPELINE_ID;
const HUBSPOT_LOGICAL_REASONING_FIELD = process.env.HUBSPOT_LOGICAL_REASONING_FIELD || 'logical_reasoning';
const HUBSPOT_VERBAL_REASONING_FIELD = process.env.HUBSPOT_VERBAL_REASONING_FIELD || 'verbal_reasoning';
const HUBSPOT_NUMERICAL_REASONING_FIELD = process.env.HUBSPOT_NUMERICAL_REASONING_FIELD || 'numerical_reasoning';

// Alias so your services stay readable
const HUBSPOT_STAGE_ACCEPTANCE_LETTER =
  process.env.HUBSPOT_STAGE_ACCEPTANCE_LETTER || HUBSPOT_ACCEPTANCE_STAGE_ID;

const HUBSPOT_STAGE_ASSESSMENTS =
  process.env.HUBSPOT_STAGE_ASSESSMENTS || HUBSPOT_ASSESSMENTS_STAGE_ID;

const GRAPH_CLIENT_ID = process.env.GRAPH_CLIENT_ID;
const GRAPH_CLIENT_SECRET = process.env.GRAPH_CLIENT_SECRET;
const GRAPH_TENANT_ID = process.env.GRAPH_TENANT_ID;
const GRAPH_SENDER_EMAIL = process.env.GRAPH_SENDER_EMAIL;

/** Internal quiz summary (SMTP / nodemailer). Falls back to EMAIL_USER if unset. */
const EMAIL_HOST = process.env.EMAIL_HOST;
const EMAIL_USER = process.env.EMAIL_USER;
const EMAIL_PASS = process.env.EMAIL_PASS;
const EMAIL_FROM = process.env.EMAIL_FROM || EMAIL_USER;
const INTERNAL_QUIZ_SUMMARY_TO = process.env.INTERNAL_QUIZ_SUMMARY_TO || EMAIL_USER;

/** Comma-separated extra origins for CORS (Render quiz UI often differs from FRONTEND_URL) */
const CORS_EXTRA_ORIGINS = String(process.env.CORS_EXTRA_ORIGINS || '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean);

module.exports = {
  PORT,
  BASE_URL,
  FRONTEND_URL,
  MONGO_URI,
  PASS_URL,
  QUIZ_PASS_PERCENT,

  HUBSPOT_CLIENT_ID,
  HUBSPOT_CLIENT_SECRET,
  HUBSPOT_REDIRECT_URI,

  HUBSPOT_ACCEPTANCE_STAGE_ID,
  HUBSPOT_ASSESSMENTS_STAGE_ID,
  HUBSPOT_PIPELINE_ID,
  HUBSPOT_LOGICAL_REASONING_FIELD,
  HUBSPOT_VERBAL_REASONING_FIELD,
  HUBSPOT_NUMERICAL_REASONING_FIELD,
  HUBSPOT_STAGE_ACCEPTANCE_LETTER,
  HUBSPOT_STAGE_ASSESSMENTS,

  GRAPH_CLIENT_ID,
  GRAPH_CLIENT_SECRET,
  GRAPH_TENANT_ID,
  GRAPH_SENDER_EMAIL,
  CORS_EXTRA_ORIGINS,

  EMAIL_HOST,
  EMAIL_USER,
  EMAIL_PASS,
  EMAIL_FROM,
  INTERNAL_QUIZ_SUMMARY_TO,

  isGraphEmailConfigured: () =>
    !!(GRAPH_CLIENT_ID && GRAPH_CLIENT_SECRET && GRAPH_TENANT_ID && GRAPH_SENDER_EMAIL),
};
